name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    needs: build-and-push 
    runs-on:
      - self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Delete old container
      run: docker rm -f frontend-order-management

    - name: Run Docker container
      run: d

    - name: Build Docker image
      run: |
        docker build -t yutt4n4/todolist .
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push yutt4n4/todolist:latest

    - name: Pull image and Deploy from DockerHub
      run: |
        docker pull yutt4n4/todolist:latest
        docker stop django_todolist || true
        docker rm django_todolist || true
        docker run -d --name django_todolist -p 8111:80 yutt4n4/todolist:latest
